name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # 🔹 permite rodar manualmente pela aba Actions

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # atualizado para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # atualizado para v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome

      # 🔹 Publica os relatórios como artefato
      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v4   # atualizado para v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
